apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev12
  labels:
    version: v4
spec:
 selector:
    matchLabels:
      app: backend
      version: v4
 template:
    metadata:
      labels:
        app: backend
        version: v4
    spec:
      containers:
       - name : "backend"
         env:
          - name: PODINFO_UI_COLOR
            value: "#4334eb"
